from django.conf import settings


def template_variables(request):
    return {'DEVILRY_STATIC_URL': settings.DEVILRY_STATIC_URL,
            'DEVILRY_URLPATH_PREFIX': settings.DEVILRY_URLPATH_PREFIX,
            'DEVILRY_LOGOUT_URL': settings.DEVILRY_LOGOUT_URL,
            'session': request.session,
            'DEVILRY_THEME_URL': settings.DEVILRY_THEME_URL,
            'DEVILRY_EXTJS_URL': settings.DEVILRY_EXTJS_URL,
            'DEVILRY_MATHJAX_URL': settings.DEVILRY_MATHJAX_URL,
            'DEVILRY_HELP_URL': settings.DEVILRY_HELP_URL,
            'DEVILRY_SYSTEM_ADMIN_EMAIL': settings.DEVILRY_SYSTEM_ADMIN_EMAIL,
            'DEVILRY_STUDENT_NO_PERMISSION_MSG': settings.DEVILRY_STUDENT_NO_PERMISSION_MSG,
            'DEVILRY_EXAMINER_NO_PERMISSION_MSG': settings.DEVILRY_EXAMINER_NO_PERMISSION_MSG,
            'DEVILRY_ADMINISTRATOR_NO_PERMISSION_MSG': settings.DEVILRY_ADMINISTRATOR_NO_PERMISSION_MSG,
            'DEVILRY_SYNCSYSTEM': settings.DEVILRY_SYNCSYSTEM}
