from optparse import make_option
from os.path import join, abspath, exists
from os import getcwd, makedirs

from django.core.management.base import BaseCommand, CommandError

from devilry.apps.administrator import restful as administrator_restful
from devilry.apps.examiner import restful as examiner_restful
from devilry.apps.student import restful as student_restful
from devilry.apps.extjshelpers.modelintegration import (restfulcls_to_extjsmodel,
                                                        get_extjs_modelname)

class Command(BaseCommand):
    help = 'Autogenerate ExtJS models from restful interfaces.'
    option_list = BaseCommand.option_list + (
        make_option('-r', '--devilry-reporoot',
            dest='reporoot',
            default=getcwd(),
            help='Devilry repository root. The direcotory that contains the devilry/ subdirectory (which contains the apps/ subdirectory).')
    ,)

    fileheader = '// Autogenerated by the dev_coreextjsmodels script. DO NOT CHANGE MANUALLY'

    def handle(self, *args, **options):
        self.reporoot = options['reporoot']
        if not exists(join(self.reporoot, 'devilry', 'apps')):
            raise CommandError('Invalid --devilry-reporoot: {0}'.format(abspath(self.reporoot)))
        self._create_files_for_module(administrator_restful)
        self._create_files_for_module(examiner_restful)
        self._create_files_for_module(student_restful)

    def _create_files_for_module(self, restfulmodule):
        modelnames = []
        dirname = self._create_dir(restfulmodule)
        for clsname in restfulmodule.__all__:
            restfulcls = getattr(administrator_restful, clsname)
            js = self._get_js_for_model(restfulcls)
            modelname = get_extjs_modelname(restfulcls)
            self._create_extjsclassfile(dirname, modelname, js)
            modelnames.append(modelname)
        self._create_requireall_file(dirname, modelnames)

    def _create_requireall_file(self, dirname, modelnames):
        requires = ',\n'.join(["    '{0}'".format(modelname) for modelname in modelnames])
        content = '{0}\nExt.require([\n{1}\n]);'.format(self.fileheader, requires)
        open(join(dirname, 'require_all.js'), 'w').write(content)

    def _get_js_for_model(self, restfulcls):
        result_fieldgroups =  restfulcls._meta.simplified._meta.resultfields.additional_aslist()
        js = restfulcls_to_extjsmodel(restfulcls, result_fieldgroups, pretty=True)
        return js + ';'


    def _create_dir(self, restfulmodule):
        clspathsplit = restfulmodule.__name__.split('.')
        if not clspathsplit[0] == 'devilry' and clspathsplit[1] == 'apps':
            raise CommandError('Invalid restful module: {0}.'.format(restfulmodule.__name__))
        appname = clspathsplit[2]
        dirname = join(self.reporoot, 'devilry', 'apps', appname, 'static', 'extjs_classes', 'apps', appname, 'simplified')
        if not exists(dirname):
            makedirs(dirname)
        return dirname

    def _create_extjsclassfile(self, dirname, modelname, js):
        clsname = modelname.split('.')[-1]
        path = join(dirname, clsname + '.js')
        open(path, 'w').write('{0}\n{1}'.format(self.fileheader, js))
