# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-08 09:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_gradingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdraft',
            name='feedbacktext_editor',
            field=models.CharField(choices=[('devilry-markdown', 'Markdown editor'), ('wysiwyg-html', 'WYSIWYG html')], default='devilry-markdown', max_length=20),
        ),
    ]
