# Generated by Django 4.2.13 on 2024-06-04 12:10

import devilry.devilry_gradingsystem.models
import devilry.utils.storageutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_gradingsystem', '0002_auto_20170108_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdraftfile',
            name='file',
            field=models.FileField(storage=devilry.utils.storageutils.get_delivery_storage, upload_to=devilry.devilry_gradingsystem.models.feedback_draft_file_upload_to),
        ),
    ]
