# Generated by Django 4.2.13 on 2024-06-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_gradingsystem', '0003_alter_feedbackdraftfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackdraftfile',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='feedbackdraftfile',
            name='saved_by',
        ),
        migrations.DeleteModel(
            name='FeedbackDraft',
        ),
        migrations.DeleteModel(
            name='FeedbackDraftFile',
        ),
    ]
