# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 16:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_group', '0018_auto_20160122_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackset',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackset',
            name='ignored_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
