# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 17:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_group', '0019_auto_20160912_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackset',
            name='ignored_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
