# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-30 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_group', '0019_auto_20160822_1945'),
        ('devilry_group', '0020_feedbackset_ignored_datetime'),
    ]

    operations = [
    ]
