# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-08 13:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_group', '0027_auto_20170207_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='period_end_time',
            field=models.DateTimeField(),
        ),
    ]
