# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-08 17:37


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_group', '0028_auto_20170208_1344'),
        ('devilry_group', '0027_auto_20170206_1146'),
    ]

    operations = [
    ]
