# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-21 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_group', '0029_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feedbacksets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackset',
            name='grading_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_feedbacksets', to=settings.AUTH_USER_MODEL),
        ),
    ]
