# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 15:54


import devilry.apps.core.models.custom_db_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devilry_group', '0031_groupcomment_v2_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksetpassedpreviousperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passed_previous_period_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbacksetpassedpreviousperiod',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedbacksetpassedpreviousperiod',
            name='passed_previous_period_type',
            field=models.CharField(choices=[('manual', 'manual'), ('auto', 'auto')], default='auto', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='assignment_long_name',
            field=devilry.apps.core.models.custom_db_fields.LongNameField(blank=True, db_index=True, default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='assignment_max_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='assignment_passing_grade_min_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='assignment_short_name',
            field=devilry.apps.core.models.custom_db_fields.ShortNameField(blank=True, default='', help_text='Up to 20 letters of lowercase english letters (a-z), numbers, underscore ("_") and hyphen ("-"). Used when the name takes too much space.', max_length=20, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='feedbackset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devilry_group.FeedbackSet'),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='grading_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='grading_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passed_previous_period_published_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='grading_published_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='period_end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='period_long_name',
            field=devilry.apps.core.models.custom_db_fields.LongNameField(blank=True, db_index=True, default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='period_short_name',
            field=devilry.apps.core.models.custom_db_fields.ShortNameField(blank=True, default='', help_text='Up to 20 letters of lowercase english letters (a-z), numbers, underscore ("_") and hyphen ("-"). Used when the name takes too much space.', max_length=20, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='feedbacksetpassedpreviousperiod',
            name='period_start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
