# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 14:02


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devilry_group', '0032_auto_20180214_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSetGradingUpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_grading_points', models.PositiveIntegerField()),
                ('old_grading_published_datetime', models.DateTimeField()),
                ('feedback_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_update_histories', to='devilry_group.FeedbackSet')),
                ('old_grading_published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
