# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 14:42


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devilry_group', '0033_feedbacksetgradingupdatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackset',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_feedbacksets', to=settings.AUTH_USER_MODEL),
        ),
    ]
