# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_comment', '0010_commentedithistory'),
        ('devilry_group', '0034_feedbackset_last_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCommentEditHistory',
            fields=[
                ('commentedithistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devilry_comment.CommentEditHistory')),
                ('visibility', models.CharField(db_index=True, max_length=50)),
                ('group_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devilry_group.GroupComment')),
            ],
            bases=('devilry_comment.commentedithistory',),
        ),
    ]
