# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-30 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_comment', '0007_auto_20170630_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentfile',
            name='v2_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
