# Generated by Django 4.2.13 on 2024-06-04 12:10

import devilry.devilry_comment.models
import devilry.utils.storageutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_comment', '0011_auto_20220421_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='file',
            field=models.FileField(blank=True, db_index=True, default='', max_length=512, storage=devilry.utils.storageutils.get_delivery_storage, upload_to=devilry.devilry_comment.models.commentfile_directory_path),
        ),
        migrations.AlterField(
            model_name='commentfileimage',
            name='image',
            field=models.FileField(blank=True, db_index=True, default='', max_length=512, storage=devilry.utils.storageutils.get_delivery_storage, upload_to=devilry.devilry_comment.models.commentfileimage_directory_path),
        ),
        migrations.AlterField(
            model_name='commentfileimage',
            name='thumbnail',
            field=models.FileField(blank=True, db_index=True, default='', max_length=512, storage=devilry.utils.storageutils.get_delivery_storage, upload_to=devilry.devilry_comment.models.commentfileimage_thumbnail_directory_path),
        ),
    ]
