#from dashboard import *
from .test_subject import *
from .test_period import *
from .test_createnewperiod import *
from .test_assignment import *
from .test_createnewassignment import *
from .test_managestudents import *
from .test_managestudents_multiselect import *
from .test_managestudents_singleselect import *
from .test_relatedusersui import *
from .test_addgroups import *
from .test_deadlines import *
from .test_exportdetailedperiodoverview import *
from .test_passedpreviousperiod import *
from .rest import *
from .views.test_assignment_update import *
