#from dashboard import *
from .subject import *
from .period import *
from .createnewperiod import *
from .assignment import *
from .createnewassignment import *
from .managestudents import *
from .managestudents_multiselect import *
from .managestudents_singleselect import *
from .rest import *
from .gradeeditor import *
from .relatedusersui import *
from .addgroups import *
from .deadlines import *
from .exportdetailedperiodoverview import *
from .passedpreviousperiod import *
from .views.test_assignment_update import *