# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_detektor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparetwocacheitem',
            name='language',
        ),
        migrations.RemoveField(
            model_name='comparetwocacheitem',
            name='parseresult1',
        ),
        migrations.RemoveField(
            model_name='comparetwocacheitem',
            name='parseresult2',
        ),
        migrations.RemoveField(
            model_name='detektorassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='detektorassignment',
            name='processing_started_by',
        ),
        migrations.AlterUniqueTogether(
            name='detektorassignmentcachelanguage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='detektorassignmentcachelanguage',
            name='detektorassignment',
        ),
        migrations.AlterUniqueTogether(
            name='detektordeliveryparseresult',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='detektordeliveryparseresult',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='detektordeliveryparseresult',
            name='detektorassignment',
        ),
        migrations.DeleteModel(
            name='CompareTwoCacheItem',
        ),
        migrations.DeleteModel(
            name='DetektorAssignment',
        ),
        migrations.DeleteModel(
            name='DetektorAssignmentCacheLanguage',
        ),
        migrations.DeleteModel(
            name='DetektorDeliveryParseResult',
        ),
    ]
