if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

alias ls="ls --color=auto"
alias ll="ls -l"
alias la="ll -A"

export PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \[\033[01;34m\] \n \$\[\033[00m\] "
