set nocompatible
syntax on
filetype plugin on
filetype plugin indent on  " enable loading the indent file for specific file types


" Common config for all filetypes
let mapleader = ","        " Redefine <Leader> from \ to ,
set ruler                  " show cursor line and column in the status line
set showmatch              " show matching brackets
set visualbell             " Stop beeping on error
set history=500            " Number of remembered commands
set backspace=2            " allow backspacing over everything in insert mode
set mouse=a                " Enable mouse in all editing modes (has no effect in gvim)
set linebreak              " Avoid breaking words when wrapping text (when using :set wrap)
set fileencoding=utf-8     " Use UTF-8
set encoding=utf-8         " Use UTF-8
set sidescroll=1           " How fast we should jump the screen when scrolling sideways
set switchbuf=usetab,split " Open file-links from the quickfix window in a existing or new tab
set tabstop=4
set shiftwidth=4           "number of spaces used by >> << and cindent
set smarttab
set expandtab
set laststatus=2           " Show filename and cursor position at the bottom of the screen
set wildmenu " turn on wild menu, try typing :h and press <Tab>
"set switchbuf=newtab,usetab " Things that switch buffers, like quickfix will open new tabs, but reuse already open tabs.
set switchbuf=useopen,split  " Things that switch buffers, like quickfix will open new windows, but reuse already open windows.
set nowrap                   " Don't wrap text
set hlsearch                 " Highlight search results
