# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-19 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_compressionutil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressedarchivemeta',
            name='backend_id',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='compressedarchivemeta',
            name='delete',
            field=models.NullBooleanField(default=None),
        ),
    ]
