# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-19 16:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_compressionutil', '0002_auto_20170119_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compressedarchivemeta',
            name='delete',
        ),
        migrations.AddField(
            model_name='compressedarchivemeta',
            name='deleted_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
