# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-20 12:29


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20160119_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_history_json', models.TextField(blank=True, default='')),
                ('assignment_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AssignmentGroup')),
            ],
        ),
    ]
