# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_assignmentgrouphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentgrouphistory',
            name='assignment_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.AssignmentGroup'),
        ),
        migrations.AlterField(
            model_name='assignmentgrouphistory',
            name='merge_history_json',
            field=models.TextField(default=b'{"merge_datetime": null, "state": null, "groups": []}'),
        ),
    ]
