# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20170124_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grading_system_plugin_id',
            field=models.CharField(blank=True, choices=[(b'devilry_gradingsystemplugin_approved', 'PASSED/FAILED. The examiner selects passed or failed.'), (b'devilry_gradingsystemplugin_points', 'POINTS. The examiner types in the number of points to award the student(s) for this assignment.')], default=b'devilry_gradingsystemplugin_approved', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_points',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='passing_grade_min_points',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
