# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20170220_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedExaminerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=15)),
                ('prefix', models.CharField(blank=True, default=b'', max_length=30)),
                ('is_hidden', models.BooleanField(default=False)),
                ('relatedexaminer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelatedExaminer')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedStudentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=15)),
                ('prefix', models.CharField(blank=True, default=b'', max_length=30)),
                ('is_hidden', models.BooleanField(default=False)),
                ('relatedstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelatedStudent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='relatedexaminersyncsystemtag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='relatedexaminersyncsystemtag',
            name='relatedexaminer',
        ),
        migrations.AlterUniqueTogether(
            name='relatedstudentsyncsystemtag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='relatedstudentsyncsystemtag',
            name='relatedstudent',
        ),
        migrations.DeleteModel(
            name='RelatedExaminerSyncSystemTag',
        ),
        migrations.DeleteModel(
            name='RelatedStudentSyncSystemTag',
        ),
        migrations.AlterUniqueTogether(
            name='relatedstudenttag',
            unique_together=set([('relatedstudent', 'prefix', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='relatedexaminertag',
            unique_together=set([('relatedexaminer', 'prefix', 'tag')]),
        ),
    ]
