# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20170220_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, default='', max_length=30)),
                ('tag', models.CharField(db_index=True, max_length=30)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_tag', to='core.Period')),
                ('relatedexaminers', models.ManyToManyField(to='core.RelatedExaminer')),
                ('relatedstudents', models.ManyToManyField(to='core.RelatedStudent')),
            ],
            options={
                'ordering': ['prefix', 'tag'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='relatedexaminersyncsystemtag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='relatedexaminersyncsystemtag',
            name='relatedexaminer',
        ),
        migrations.AlterUniqueTogether(
            name='relatedstudentsyncsystemtag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='relatedstudentsyncsystemtag',
            name='relatedstudent',
        ),
        migrations.DeleteModel(
            name='RelatedExaminerSyncSystemTag',
        ),
        migrations.DeleteModel(
            name='RelatedStudentSyncSystemTag',
        ),
        migrations.AlterUniqueTogether(
            name='periodtag',
            unique_together=set([('period', 'prefix', 'tag')]),
        ),
    ]
