# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-23 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170303_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodtag',
            name='tag',
            field=models.TextField(db_index=True, max_length=30),
        ),
    ]
