# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-27 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170223_1643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relatedexaminertag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='relatedexaminertag',
            name='relatedexaminer',
        ),
        migrations.AlterUniqueTogether(
            name='relatedstudenttag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='relatedstudenttag',
            name='relatedstudent',
        ),
        migrations.DeleteModel(
            name='RelatedExaminerTag',
        ),
        migrations.DeleteModel(
            name='RelatedStudentTag',
        ),
    ]
