# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20170523_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodtag',
            name='tag',
            field=models.TextField(db_index=True),
        ),
    ]
