# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-20 15:15


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20170523_1748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='node',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='node',
            name='parentnode',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='parentnode',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
