# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 11:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20170621_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentgroup',
            name='internal_is_being_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
