# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_assignmentgroup_internal_is_being_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.DateTimeField(help_text='Start time and end time defines when the period is active.', verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.DateTimeField(help_text='Start time and end time defines when the period is active.', verbose_name='Start time'),
        ),
    ]
