# Generated by Django 3.2.6 on 2022-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210427_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='examiner_self_assign_limit',
            field=models.PositiveIntegerField(default=1, help_text='The max number of examiners that are allowed to self-assign to each project group within the assignment.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='examiners_can_self_assign',
            field=models.BooleanField(default=False, help_text='Select this if you want examiners to be able to self-assign to the assignment.', verbose_name='Can examiners assign themselves to the assignment?'),
        ),
    ]
