# Generated by Django 4.2.13 on 2024-06-04 12:10

import devilry.apps.core.models.static_feedback
import devilry.utils.storageutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20220519_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfeedbackfileattachment',
            name='file',
            field=models.FileField(storage=devilry.utils.storageutils.get_delivery_storage, upload_to=devilry.apps.core.models.static_feedback.staticfeedback_fileattachment_upload_to),
        ),
    ]
