# Generated by Django 4.2.13 on 2024-06-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_staticfeedbackfileattachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='alias_delivery',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='copy_of',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='last_feedback',
        ),
        migrations.AlterUniqueTogether(
            name='filemeta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='filemeta',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='staticfeedback',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='staticfeedback',
            name='saved_by',
        ),
        migrations.RemoveField(
            model_name='staticfeedbackfileattachment',
            name='staticfeedback',
        ),
        migrations.RemoveField(
            model_name='assignmentgroup',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='assignmentgroup',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='assignmentgroup',
            name='last_deadline',
        ),
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='FileMeta',
        ),
        migrations.DeleteModel(
            name='StaticFeedback',
        ),
        migrations.DeleteModel(
            name='StaticFeedbackFileAttachment',
        ),
    ]
