# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 11:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_qualifiesforexam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready for export'), ('almostready', 'Most students are ready for export'), ('notready', 'Not ready for export (retracted)')], max_length=30),
        ),
    ]
