# Generated by Django 3.1.8 on 2021-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_qualifiesforexam', '0003_auto_20170629_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiesforfinalexam',
            name='qualifies',
            field=models.BooleanField(null=True),
        ),
    ]
