# Generated by Django 3.2.15 on 2022-09-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20220519_1043'),
        ('devilry_qualifiesforexam', '0004_auto_20210427_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedQualifiesForFinalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifies', models.BooleanField(null=True)),
                ('relatedstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relatedstudent')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='devilry_qualifiesforexam.status')),
            ],
        ),
    ]
