# Generated by Django 5.2.12 on 2026-03-24 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_delivery_alias_delivery_and_more'),
        ('devilry_qualifiesforexam', '0006_status_plugin_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.CharField(blank=True, max_length=500, null=True)),
                ('plugin_data', models.JSONField(blank=True, default=dict, null=True)),
                ('processing_started_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('processing_completed_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('processing_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('error', 'Error')], default='not_started', max_length=32)),
                ('processing_status_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
        ),
        migrations.CreateModel(
            name='DraftQualifiesForFinalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifies', models.BooleanField(default=False)),
                ('relatedstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relatedstudent')),
                ('draft_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='devilry_qualifiesforexam.draftstatus')),
            ],
        ),
    ]
