# Generated by Django 5.2.13 on 2026-04-29 12:35

from django.db import migrations

PLUGIN = "devilry_qualifiesforexam_plugin_approved.plugin_select_assignments"


def convert_plugin_data_list_to_dict(apps, _schema_editor):
    Status = apps.get_model("devilry_qualifiesforexam", "Status")
    statuses = Status.objects.filter(plugin=PLUGIN)
    for status in statuses:
        if isinstance(status.plugin_data, list):
            status.plugin_data = {"qualifying_assignment_ids": status.plugin_data}
            status.save(update_fields=["plugin_data"])


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_qualifiesforexam', '0007_draftstatus_draftqualifiesforfinalexam'),
    ]

    operations = [
        migrations.RunPython(
            convert_plugin_data_list_to_dict,
            migrations.RunPython.noop,
        ),
    ]
