# Generated by Django 5.2.13 on 2026-05-04 11:58

from django.db import migrations
import json

PLUGIN = "devilry_qualifiesforexam_plugin_approved.plugin_select_assignments"

def convert_plugin_data_json_stringlist_to_dict(apps, _schema_editor):
    """
    This migration fixes an issue that originated from the the Status.plugin_data JSONField being introduced.

    The issue is that some Status records have plugin_data stored as a JSON string of a list of integers, instead of a 
    dict with the key "qualifying_assignment_ids" mapping to the list of integers.
    """
    Status = apps.get_model("devilry_qualifiesforexam", "Status")
    statuses = Status.objects.filter(plugin=PLUGIN)
    for status in statuses:
        if isinstance(status.plugin_data, str):
            try:
                json_data = json.loads(status.plugin_data)
                if isinstance(json_data, list) and all(isinstance(item, int) for item in json_data):
                    status.plugin_data = {"qualifying_assignment_ids": json_data}
                    status.save(update_fields=["plugin_data"])
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_qualifiesforexam', '0008_auto_20260429_1435'),
    ]

    operations = [
        migrations.RunPython(convert_plugin_data_json_stringlist_to_dict),
    ]
