#!/usr/bin/env python
if __name__ == '__main__':
    import sys
    import logging
    from utils import execute, logging_startup, showhelp

    try:
        command = sys.argv[1]
        args = sys.argv[2:]
    except IndexError:
        showhelp()
        raise SystemExit()

    args = logging_startup(args)
    execute(command, args)
