#!/bin/bash

# To use this script, you must first checkout
# git@github.com:devilry/devilry.github.com.git
# into this directory (it should be in doc/devilry.github.com).
#
# After running this script, you must manually commit and push
# devilry.github.com.

VERSION=dev
REPODIR=devilry.github.com
OUTDIR=$REPODIR/$VERSION
INDIR=build/html


make clean html
rm -rf $OUTDIR
cp -r $INDIR $OUTDIR
#sphinxtogithub $OUTDIR
cd $REPODIR; git add $VERSION; cd ..
