# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempMergeId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_id', models.PositiveIntegerField()),
                ('from_id', models.PositiveIntegerField()),
                ('model_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tempmergeid',
            unique_together=set([('to_id', 'from_id', 'model_name')]),
        ),
    ]
