# Generated by Django 3.1.8 on 2021-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_account', '0006_auto_20160120_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='is_primary',
            field=models.BooleanField(blank=True, choices=[(None, 'No'), (True, 'Yes')], help_text='Your primary email is the email address used when we need to display a single email address.', null=True, verbose_name='Is this your primary email?'),
        ),
        migrations.AlterField(
            model_name='username',
            name='is_primary',
            field=models.BooleanField(blank=True, choices=[(None, 'No'), (True, 'Yes')], help_text='Your primary username is shown alongside your full name to identify you to teachers, examiners and other students.', null=True, verbose_name='Is this your primary username?'),
        ),
    ]
