# Generated by Django 3.2.13 on 2022-05-10 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210427_1350'),
        ('devilry_account', '0007_auto_20210427_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodUserGuidelineAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devilryrole', models.CharField(db_index=True, max_length=20)),
                ('accepted_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guidelines_version', models.CharField(db_index=True, max_length=20)),
                ('matched_regex', models.TextField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='perioduserguidelineacceptance',
            constraint=models.UniqueConstraint(fields=('user', 'period', 'devilryrole', 'guidelines_version'), name='unique_user_period_role_version'),
        ),
    ]
