warning:
	@echo "This has been replaced by devilryadmin.py (In devilry/devilryadmin/)."
	@echo "Recommended installation procedure is to add an alias to"
	@echo "devilryadmin.py, or a symlink to a directory on your path."
	@echo "You should not add devilry/devilryadmin/ to your path, since that"
	@echo "will add all the other executables in the directory to your path as well."
	@echo
	@echo "More info here: https://github.com/devilry/devilry-django/issues/114"
	@echo
	@echo "The parts that have not been ported yet are still available in Makefile.deprecated"
	@echo "Use 'make -f Makefile.deprecated' to access it."
