from jasmine import *
from actionlist import *
from shortcuts import *
from dashboard import *
from subject import *
from assignment import *
from createnewassignment import *
from managestudents import *
from rest import *
