from .rest.test_add_delivery import TestRestAddDeliveryView
from .rest.test_open_groups import TestRestOpenGroups
from .rest.test_aggregated_groupinfo import TestRestAggregatedGroupInfo
from .rest.test_recent_deliveries import TestRestRecentDeliveries
from .rest.test_recent_feedbacks import TestRestRecentFeedbacks
from .rest.test_find_groups import TestRestFindGroups
from .rest.test_results import TestRestResults

from .views.test_upload_deliveryfile import TestUploadDeliveryFile
from .views.test_projectgroup_overview import TestProjectGroupOverviewView
from .views.test_groupinvite_respond import TestGroupInviteRespondView
from .views.test_groupinvite_delete import TestGroupInviteDeleteView
from .views.test_frontpage import TestFrontpage
from .views.test_student_browseview import TestBrowseView
from .views.test_student_semesteroverview import TestSemesterOverview
from .views.test_groupdetails import TestGroupDetailsView
from .test_templatetags import TestDevilryStudentFeedbackTags
from .test_models import TestUploadedDeliveryFile
