# Generated by Django 2.2.1 on 2019-06-24 10:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_import_v2database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedmodel',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
