# Generated by Django 3.1.8 on 2021-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_import_v2database', '0002_auto_20190624_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedmodel',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
