# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_auto_20160119_0337'),
        ('devilry_group', '0024_auto_20170107_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGroupCachedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_attempt_count', models.PositiveIntegerField(default=0)),
                ('public_total_comment_count', models.PositiveIntegerField(default=0)),
                ('public_student_comment_count', models.PositiveIntegerField(default=0)),
                ('public_examiner_comment_count', models.PositiveIntegerField(default=0)),
                ('public_admin_comment_count', models.PositiveIntegerField(default=0)),
                ('public_total_imageannotationcomment_count', models.PositiveIntegerField(default=0)),
                ('public_student_imageannotationcomment_count', models.PositiveIntegerField(default=0)),
                ('public_examiner_imageannotationcomment_count', models.PositiveIntegerField(default=0)),
                ('public_admin_imageannotationcomment_count', models.PositiveIntegerField(default=0)),
                ('public_student_file_upload_count', models.PositiveIntegerField(default=0)),
                ('first_feedbackset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='devilry_group.FeedbackSet')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_data', to='core.AssignmentGroup')),
                ('last_feedbackset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='devilry_group.FeedbackSet')),
                ('last_published_feedbackset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='devilry_group.FeedbackSet')),
            ],
        ),
    ]
