# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-08 14:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_dbcache', '0003_auto_20170108_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentgroupcacheddata',
            name='last_public_comment_by_examiner_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='assignmentgroupcacheddata',
            name='last_public_comment_by_student_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
