# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_dbcache', '0004_auto_20170108_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentgroupcacheddata',
            name='candidate_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='assignmentgroupcacheddata',
            name='examiner_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
