# Generated by Django 5.2.4 on 2025-07-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_dbcache', '0005_auto_20170124_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentgroupcacheddata',
            name='public_student_attempts_with_delivered_files',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
