from django.conf.urls.defaults import *



urlpatterns = patterns('devilry.apps.examiner',
    url(r'^$',
        'views.list_assignments',
        name='devilry-examiner-list_assignments'),

    url(r'^list-groups/(?P<assignment_id>\d+)$',
        'views.list_assignmentgroups',
        name='devilry-examiner-list_assignmentgroups'),
    url(r'^list-groups/json/(?P<assignment_id>\d+)$',
        'views.list_assignmentgroups_json',
        name='devilry-examiner-list_assignmentgroups_json'),
    url(r'^assignments/(?P<assignmentgroup_id>\d+)$',
        'views.show_assignmentgroup',
        name='devilry-examiner-show_assignmentgroup'),
    url(r'^assignments-as-examiner/(?P<assignmentgroup_id>\d+)$',
        'views.show_assignmentgroup',
        kwargs={'is_admin':False},
        name='devilry-examiner-show_assignmentgroup-as-examiner'),
    url(r'^assignments-as-admin/(?P<assignmentgroup_id>\d+)$',
        'views.show_assignmentgroup',
        kwargs={'is_admin':True},
        name='devilry-examiner-show_assignmentgroup-as-admin'),

    url(r'^assignments/(?P<assignmentgroup_id>\d+)/edit-deadline/(?P<deadline_id>\d+)$',
        'views.edit_deadline',
        name='devilry-examiner-edit_deadline'),
    url(r'^assignments/(?P<assignmentgroup_id>\d+)/create-deadline$',
        'views.edit_deadline',
        name='devilry-examiner-create_deadline'),

    url(r'^open-group/(?P<assignmentgroup_id>\d+)$',
        'views.open_assignmentgroup',
        name='devilry-examiner-open_assignmentgroup'),
    url(r'^close-group/(?P<assignmentgroup_id>\d+)$',
        'views.close_assignmentgroup',
        name='devilry-examiner-close_assignmentgroup'),
    url(r'^delete-deadline/(?P<assignmentgroup_id>\d+)/(?P<deadline_id>\d+)$',
        'views.delete_deadline',
        name='devilry-examiner-delete_deadline'),
    url(r'^assignments/(?P<assignment_id>\d+)/download_file_collection_as_zip$',
        'views.download_file_collection',
        kwargs={"archive_type":"zip"},
        name='devilry-examiner-download_file_collection_as_zip'),
    url(r'^assignments/(?P<assignment_id>\d+)/download_file_collection_as_tar$',
        'views.download_file_collection',
        kwargs={"archive_type":"tar.gz"},
        name='devilry-examiner-download_file_collection_as_tar'),
    
    url(r'^assignments/(?P<assignment_id>\d+)/show_emails$',
        'views.show_emails',
        name='devilry-examiner-show_emails'),

    url(r'^edit-feedback/(?P<delivery_id>\d+)/download_delivery_as_tar$',
        'views.download_delivery',
        kwargs={"archive_type":"tar.gz"},
        name='devilry-examiner-download_delivery_as_tar'),
    url(r'^edit-feedback/(?P<delivery_id>\d+)/download_delivery_as_zip$',
        'views.download_delivery',
        kwargs={"archive_type":"zip"},
        name='devilry-examiner-download_delivery_as_zip'),
                       
    url(r'^edit-feedback/(?P<delivery_id>\d+)/download_group_deliveries_as_tar$',
        'views.download_group_deliveries',
        kwargs={"archive_type":"tar.gz"},
        name='devilry-examiner-download_group_deliveries_as_tar'),
    url(r'^edit-feedback/(?P<delivery_id>\d+)/download_group_deliveries_as_zip$',
        'views.download_group_deliveries',
        kwargs={"archive_type":"zip"},
        name='devilry-examiner-download_group_deliveries_as_zip'),
                     
    url(r'^edit-feedback/(?P<delivery_id>\d+)$',
        'views.edit_feedback',
        name='devilry-examiner-edit-feedback'),
    url(r'^edit-feedback-as-examiner/(?P<delivery_id>\d+)$',
        'views.edit_feedback',
        kwargs={"is_admin":False},
        name='devilry-examiner-edit-feedback-as-examiner'),
    url(r'^edit-feedback-as-admin/(?P<delivery_id>\d+)$',
        'views.edit_feedback',
        kwargs={"is_admin":True},
        name='devilry-examiner-edit-feedback-as-admin'),

    url(r'^assignments/(?P<assignment_id>\d+)/create-deadlines$',
        'views.create_deadlines',
        name='devilry-examiner-create_deadlines'),
    url(r'^assignments/(?P<assignment_id>\d+)/clear-deadlines$',
        'views.clear_deadlines',
        name='devilry-examiner-clear_deadlines'),

    url(r'^assignments/(?P<assignment_id>\d+)/open-many-groups$',
        'views.open_many_groups',
        name='devilry-examiner-open_many_groups'),
    url(r'^assignments/(?P<assignment_id>\d+)/close_many_groups$',
        'views.close_many_groups',
        name='devilry-examiner-close_many_groups'),

    url(r'^assignments/(?P<assignment_id>\d+)/publish_many_groups$',
        'views.publish_many_groups',
        name='devilry-examiner-publish_many_groups'),
)
