# Generated by Django 4.2.13 on 2024-06-04 12:10

import devilry.devilry_student.models
import devilry.utils.storageutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddeliveryfile',
            name='uploaded_file',
            field=models.FileField(storage=devilry.utils.storageutils.get_temporary_storage, upload_to=devilry.devilry_student.models.uploaded_deliveryfile_path),
        ),
    ]
