# Generated by Django 4.2.13 on 2024-06-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_student', '0002_alter_uploadeddeliveryfile_uploaded_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedDeliveryFile',
        ),
    ]
