from .test_auth import *
from .test_group import *
from .test_createnewassignment import *
from .test_subject import *
from .test_period import *
from .test_assignment import *
from .test_relateduser import *
from .test_relateduser_assignment_ro import *
from .test_allwhereisadmin import *
from .test_deadlinesbulk import *
from .test_popfromgroup import *
from .test_mergeintogroup import *
from .test_aggregated_groupinfo import *
from .test_passedinpreviousperiod import *
from .test_detailedperiodoverview import TestRestDetailedPeriodOverview
from .test_examinerstats import TestRestExaminerStats