# Generated by Django 4.2.1 on 2023-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilry_message', '0002_auto_20210427_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='context_type',
            field=models.CharField(choices=[('other', 'Other'), ('comment_delivery', 'Comment or delivery'), ('deadline_moved', 'Deadline moved'), ('new_attempt', 'New attempt'), ('feedback', 'Feedback'), ('feedback_updated', 'Grading updated'), ('group_invite_invitation', 'Group invitation: invitation'), ('group_invite_accepted', 'Group invitation: accepted'), ('group_invite_rejected', 'Group invitation: rejected')], default='other', max_length=255),
        ),
    ]
