#!/bin/bash

_devilryadmin_completion()
{
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    if [[ ${prev} == "devilryadmin.py" ]] ; then
        actions="$(devilryadmin.py --completionlist)"
        COMPREPLY=( $(compgen -W "${actions}" ${cur}) )
        return 0
    else
        actions="$(devilryadmin.py ${prev} --completionlist)"
        COMPREPLY=( $(compgen -W "${actions}" -- ${cur}) )
        return 0
    fi
}

complete -F _devilryadmin_completion devilryadmin.py
